## 1) Input and output files

In [13]:
#open coordinates of molecules as .csv

import pandas as pd

my_coord = pd.read_csv("coordinates-resid9.csv")


my_coord  #open csv file

output_file = "coordinates-resid9_output.csv"

        X      Y       Z
0  -1.908 -1.475  -9.137
1  -2.665 -1.579 -10.404
2  -0.802 -2.443  -8.959
3  -1.349  0.015  -8.963
4  -2.197  1.013  -8.364
5  -1.404  1.838  -7.371
6  -1.403  1.252  -6.038
7   0.079  2.022  -7.694
8   0.474  3.333  -7.309
9   0.799  1.015  -6.797
10 -0.066  1.231  -5.559
11  0.047  0.150  -4.546
12 -0.045  0.513  -3.217
13 -0.212  1.665  -2.857
14  0.066 -0.526  -2.326
15  0.254 -1.860  -2.624
16  0.334 -2.680  -1.707
17  0.339 -2.154  -4.021
18  0.234 -1.163  -4.914

## 2) Change coordinates so base flips